Models/BillOfMaterialsExpanded.cs
using System;
using System.Collections.Generic;

namespace MVC_Test.Models
{
    public class BillOfMaterialsExpanded
    {
        public Guid BillOfMaterialsExpandedId { get; set; }
        public int? BomLevel { get; set; }
        public string TopLevelItem { get; set; }
        public string TopLevelDescription { get; set; }
        public string ParentItem { get; set; }
        public string ParentDescription { get; set; }
        public string ComponentItem { get; set; }
        public string ComponentDescription { get; set; }
        public decimal? QuantityPerTop { get; set; }
        public decimal? QuantityPerParent { get; set; }
        public string PurchasedOrManufactured { get; set; }
        public decimal? ScrapPercentage { get; set; }
        public int? BomSequence { get; set; }
        public string FullSequence { get; set; }
        public string ParentId { get; set; }
        public string HasChild { get; set; }
        public decimal? StandardCost { get; set; }
        public decimal? LineCost { get; set; }
        public string ManufacturerCodes { get; set; }
        public DateTime? BomDate { get; set; }
        public string BomReference { get; set; }
        public string BomRelease { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MVC_Test.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BillOfMaterialsExpandedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Test.Data;
using MVC_Test.Models;

namespace MVC_Test.Controllers
{
    public class BillOfMaterialsExpandedController : Controller
    {
        private readonly EncostaContext _context;

        public BillOfMaterialsExpandedController(EncostaContext context)
        {
            _context = context;
        }

        // GET: BillOfMaterialsExpanded
        public async Task<IActionResult> Index()
        {
            return View(await _context.BillOfMaterialsExpanded.Take(20).ToListAsync());
        }

        // GET: BillOfMaterialsExpanded/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billOfMaterialsExpanded = await _context.BillOfMaterialsExpanded
                .FirstOrDefaultAsync(m => m.BillOfMaterialsExpandedId == id);
            if (billOfMaterialsExpanded == null)
            {
                return NotFound();
            }

            return View(billOfMaterialsExpanded);
        }

        // GET: BillOfMaterialsExpanded/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BillOfMaterialsExpanded/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillOfMaterialsExpandedId,BomLevel,TopLevelItem, TopLevelDescription,ParentItem,ParentDescription,ComponentItem,ComponentDescription,QuantityPerTop,QuantityPerParent,PurchasedOrManufactured,ScrapPercentage,BomSequence,FullSequence,ParentId,HasChild,StandardCost,LineCost,ManufacturerCodes,BomDate,BomReference,BomRelease")] BillOfMaterialsExpanded billOfMaterialsExpanded)
        {
            if (ModelState.IsValid)
            {
                billOfMaterialsExpanded.BillOfMaterialsExpandedId = Guid.NewGuid();
                _context.Add(billOfMaterialsExpanded);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(billOfMaterialsExpanded);
        }

        // GET: BillOfMaterialsExpanded/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billOfMaterialsExpanded = await _context.BillOfMaterialsExpanded.FindAsync(id);
            if (billOfMaterialsExpanded == null)
            {
                return NotFound();
            }
            return View(billOfMaterialsExpanded);
        }

        // POST: BillOfMaterialsExpanded/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("BillOfMaterialsExpandedId,BomLevel,TopLevelItem,TopLevelDescription,ParentItem,ParentDescription,ComponentItem,ComponentDescription,QuantityPerTop,QuantityPerParent,PurchasedOrManufactured,ScrapPercentage,BomSequence,FullSequence,ParentId,HasChild,StandardCost,LineCost,ManufacturerCodes,BomDate,BomReference,BomRelease")] BillOfMaterialsExpanded billOfMaterialsExpanded)
        {
            if (id != billOfMaterialsExpanded.BillOfMaterialsExpandedId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(billOfMaterialsExpanded);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillOfMaterialsExpandedExists(billOfMaterialsExpanded.BillOfMaterialsExpandedId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(billOfMaterialsExpanded);
        }

        // GET: BillOfMaterialsExpanded/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billOfMaterialsExpanded = await _context.BillOfMaterialsExpanded
                .FirstOrDefaultAsync(m => m.BillOfMaterialsExpandedId == id);
            if (billOfMaterialsExpanded == null)
            {
                return NotFound();
            }

            return View(billOfMaterialsExpanded);
        }

        // POST: BillOfMaterialsExpanded/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var billOfMaterialsExpanded = await _context.BillOfMaterialsExpanded.FindAsync(id);
            _context.BillOfMaterialsExpanded.Remove(billOfMaterialsExpanded);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillOfMaterialsExpandedExists(Guid id)
        {
            return _context.BillOfMaterialsExpanded.Any(e => e.BillOfMaterialsExpandedId == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_Test.Models;

namespace MVC_Test.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //public IActionResult BillOfMaterialsExpanded()
        //{
        //    return View();
        //}


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/BillOfMaterialsExpanded/Create.cshtml
@model MVC_Test.Models.BillOfMaterialsExpanded

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BillOfMaterialsExpanded</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillOfMaterialsExpandedId" class="control-label"></label>
                <input asp-for="BillOfMaterialsExpandedId" class="form-control" />
                <span asp-validation-for="BillOfMaterialsExpandedId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BomLevel" class="control-label"></label>
                <input asp-for="BomLevel" class="form-control" />
                <span asp-validation-for="BomLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TopLevelItem" class="control-label"></label>
                <input asp-for="TopLevelItem" class="form-control" />
                <span asp-validation-for="TopLevelItem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TopLevelDescription" class="control-label"></label>
                <input asp-for="TopLevelDescription" class="form-control" />
                <span asp-validation-for="TopLevelDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentItem" class="control-label"></label>
                <input asp-for="ParentItem" class="form-control" />
                <span asp-validation-for="ParentItem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentDescription" class="control-label"></label>
                <input asp-for="ParentDescription" class="form-control" />
                <span asp-validation-for="ParentDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComponentItem" class="control-label"></label>
                <input asp-for="ComponentItem" class="form-control" />
                <span asp-validation-for="ComponentItem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComponentDescription" class="control-label"></label>
                <input asp-for="ComponentDescription" class="form-control" />
                <span asp-validation-for="ComponentDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityPerTop" class="control-label"></label>
                <input asp-for="QuantityPerTop" class="form-control" />
                <span asp-validation-for="QuantityPerTop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityPerParent" class="control-label"></label>
                <input asp-for="QuantityPerParent" class="form-control" />
                <span asp-validation-for="QuantityPerParent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchasedOrManufactured" class="control-label"></label>
                <input asp-for="PurchasedOrManufactured" class="form-control" />
                <span asp-validation-for="PurchasedOrManufactured" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScrapPercentage" class="control-label"></label>
                <input asp-for="ScrapPercentage" class="form-control" />
                <span asp-validation-for="ScrapPercentage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BomSequence" class="control-label"></label>
                <input asp-for="BomSequence" class="form-control" />
                <span asp-validation-for="BomSequence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullSequence" class="control-label"></label>
                <input asp-for="FullSequence" class="form-control" />
                <span asp-validation-for="FullSequence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <input asp-for="ParentId" class="form-control" />
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HasChild" class="control-label"></label>
                <input asp-for="HasChild" class="form-control" />
                <span asp-validation-for="HasChild" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StandardCost" class="control-label"></label>
                <input asp-for="StandardCost" class="form-control" />
                <span asp-validation-for="StandardCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LineCost" class="control-label"></label>
                <input asp-for="LineCost" class="form-control" />
                <span asp-validation-for="LineCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturerCodes" class="control-label"></label>
                <input asp-for="ManufacturerCodes" class="form-control" />
                <span asp-validation-for="ManufacturerCodes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BomDate" class="control-label"></label>
                <input asp-for="BomDate" class="form-control" />
                <span asp-validation-for="BomDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BomReference" class="control-label"></label>
                <input asp-for="BomReference" class="form-control" />
                <span asp-validation-for="BomReference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BomRelease" class="control-label"></label>
                <input asp-for="BomRelease" class="form-control" />
                <span asp-validation-for="BomRelease" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BillOfMaterialsExpanded/Delete.cshtml
@model MVC_Test.Models.BillOfMaterialsExpanded

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BillOfMaterialsExpanded</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BomLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BomLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TopLevelItem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TopLevelItem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TopLevelDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TopLevelDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentItem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentItem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComponentItem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComponentItem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComponentDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComponentDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityPerTop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityPerTop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityPerParent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityPerParent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PurchasedOrManufactured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PurchasedOrManufactured)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ScrapPercentage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ScrapPercentage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BomSequence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BomSequence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullSequence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullSequence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasChild)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasChild)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StandardCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StandardCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LineCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LineCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturerCodes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturerCodes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BomDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BomDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BomReference)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BomReference)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BomRelease)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BomRelease)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BillOfMaterialsExpandedId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
    
    @(Html.DevExtreme().TreeList()
        .ID("employees")
        .DataSource(new JS("employees"))
        .RootValue(-1)
        .KeyExpr("ID")
        .ParentIdExpr("Head_ID")
        .Columns(columns => {
                                columns.Add()
                                    .DataField("Title")
                                    .Caption("Position");

                                columns.Add().DataField("Full_Name");

                                columns.Add().DataField("City");

                                columns.Add().DataField("State");

                                columns.Add().DataField("Mobile_Phone");

                                columns.Add()
                                    .DataField("Hire_Date")
                                    .DataType(GridColumnDataType.Date);
        })
        .ShowRowLines(true)
        .ShowBorders(true)
        .ColumnAutoWidth(true)
        .ExpandedRowKeys(new[] { 1 })
        )

    <script src="~/data/employeesPS.js"></script>

</div>

Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - MVC_Test</title>

@*    <title>MVC_Test</title>*@
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>


<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Test</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="BillOfMaterialsExpanded" asp-action="Index">Bom Expanded Tree List</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - MVC_Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>


@*<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">MVC_Test</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="active nav-item"><a href="#" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                <li class="nav-item"><a href="#contact" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>*@

</html>